### ISSUE TITLE
Have BSQ on other exchanges

### ISSUE THREAD

**Issue by leo816** [bisq-network/proposals#371] opened 2022-03-16 08:21 UTC
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

I agree that it goes against BISQ's principles to be on centralized exchanges BUT if you view BSQ as equity in the project, what you are doing is giving people another way of getting to know more about bisq. We can talk shit about centralized exchanges all day but the truth is they have done an incredible job in being that bridge between the fiat world and crypto. Most people in crypto today are here because of coinbase, binance and others. Bitcoin is, and has always been in all shitcoin-casinos and no one seems to mention it, and that doesn't take anything away from Bitcoin. Volatility due to more liquidity isn't bad, in fact is necessary for growth. Giving it more exposure and using channels like CEXs to have more ways to attract people is a great thing. For bisq it would mean more liquidity, a potential increase in price thus giving back to contributors and eventually have more users which would scale the project even more. 

We have BSQ-BTC swaps, literally the first atomic swaps on bitcoin, huge! but no one knows about it. I do believe in a slow steady growth but at some point we have to make BSQ more accessible and get more people to know about what is happening here. Using the api for trading bots will be an awesome volume boost but there needs to be a larger pool of people that have access to BSQ.

How come BSQ is not even on coinmarketcap? what needs to be done to be there?

Already on CEXs:
- Sovryn [(SOV)](https://coinmarketcap.com/es/currencies/sovryn/) in kucoin, gate.io, uniswap...
- Celcius [(CEL)](https://coinmarketcap.com/es/currencies/celsius/) FTX, Liquid, uniswap, gate.io..
- Nexo [NEXO](https://coinmarketcap.com/es/currencies/nexo/) Huobi Global, Bitfinex, FTX...
- RSK Smart Bitcoin [RBTC](https://coinmarketcap.com/es/currencies/rsk-smart-bitcoin/markets/) Kucoin, Bitfinex..

What needs to be done to make this happen? I'm sure with Bisq there will be more technical difficulties than with other projects but I strongly believe this will help, please share your ideas and I'm looking forward to hear other people's thoughts.

**Comment by flix1** [comment] 2022-03-16 10:35
Getting listed on other exchanges will be a difficult process and if liquidity there is low we would be in the same situation. I do agree it should be done, but not that it is the priority or that it will solve the problem.

What would actually solve the issue of low BSQ liquidity?

**Market makers**. 

This is exactly what market makers do! For a small fee (1-3%) they ensure that there is a minimum of market depth and liquidity every day. https://bisq.wiki/How_to_be_a_market_maker_on_Bisq

Bonus points if you can automate it and have a market making **bot** do the work. It should be easier on the BSQ/BTC market because of atomic swaps.

Market makers will solve the **liquidity** issue by bridging the gap between burning man and sellers. Market makers do **NOT** solve the **price** issue... if demand for BSQ is low, price will continue to trend down. However now that Bisq DAO is profitable and burning more BSQ than it issues every month, the price should trend up over the long term.

**Comment by Conza88** [comment] 2022-03-16 11:34
> For bisq it would mean more liquidity,

I don't think it would. I think there would be a net loss. I am here, would I be if it started out as not being just 'coloured-bitcoin' but more a kin to a shit coin? No. Too easy to dismiss. 

> We have BSQ-BTC swaps, literally the first atomic swaps on bitcoin, huge! but no one knows about it.

Because of the customer experience, not branding or marketing. Consider why folks go central exchanges route compared to decentralised ; 
(1) cheaper fee's 
(2) UX 
(3) Liquidity

You get more of 3 by improving (1) and (2). Single transaction is important for (1). The multi-offer proposal helps with 3; and local community growth which is non-existent atm given basic economics (gravitating to bigger markets). 

UX was designed but looks like Bisq 2 will have to do those changes. 

The increased value comes from improving the product/customer experience; not 'selling out' to shill elsewhere to get more demand. I don't think you will get much at all; and will kill brand respect immediately. 

> How come BSQ is not even on coinmarketcap? what needs to be done to be there?

Because its not a shitcoin.

**Comment by MwithM** [comment] 2022-03-16 12:22
The AOPP issue should teach Bisq that inviting people to use middleman services is not a good strategy.
Bisq can't ban other exchanges from listing BSQ, but actively listing it in CEX's is a bad idea, no matter if it improves liquidity and awareness. If a CEX listed BSQ, Bisq should encourage to their users to stop using it, not the opposite.
At least the AOPP defenders claimed that it made it easier for user to get control of their private keys. In this case it would be exactly the opposite.

I think that having BSQ listed on coingecko, coinmarketcap etc won't hurt. It's just a list.

BSQ is already BTC, the best way to trade it has to be at Bisq. BSQ swaps is a huge feature but it needs to grow together with Bisq's utility.

I would give to this proposal a 180º turn:
Why Bisq did not list every possible asset so any shitcoiner or simply especulator could use Bisq?
For Bisq 2, I think that alt trading should have lower trading fees (mediation is easier) and any coin with a min amount of volume at the social trading protocol should end up being listed.

**Comment by Conza88** [comment] 2022-03-16 12:36
> Why Bisq did not list every possible asset so any shitcoiner or simply especulator could use Bisq?

Because any time or resources wasted on shit like that—signals Bisq isn't serious about building the foundations for the future of money (outside the centralised KYC world). 

The simple value proposition is BTC, non-KYC, decentralised exchange to go with decentralised money. 

A straight forward scam free experience with lowish fee's, liquidity, and a growing non-KYC community that values privacy & using the tools. 

Why in the world would you want to jeopardise that? The issues are clear - fixing them is vital... crap side shows to allow 'trading for shit coin scam artists' flies directly in the fact of the value proposition and branding Bisq has built.

**Comment by w0000000t** [comment] 2022-03-16 15:11
All the participants in this thread do know more than me about crypto "politics", so I am not going to argue about the above points made in reply to leo (which, I must admit, are all good points, or at least sound so to someone who knows less than you about crypto politics).
I placed a thumbs up on OP as I still would like to know BSQ is listed on other exchanges as well, yet I understand that Bisq going out of its way to make CEXes list BSQ, would look like asking for help to our enemy 😄

**Comment by pazza83** [comment] 2022-03-21 00:08
Long term I would like to see BSQ on other exchanges. For the moment however I think it is a not ready yet, maybe the numbers below would need to be at least 10-20 times higher:

Current numbers taken from DAO section:

- BSQ market cap: $4,760,840
- Number of BSQ trades per month: ~ 200
- Trade volume of BSQ trades per month: ~ $200,000

I think if BSQ grows organically then listing on other exchanges could be considered.

I also like the idea that if someone currently wants to get BSQ they will need to use the Bisq app. I also think having BSQ trades on centralized exchanges is contrary to what Bisq is looking to do. Also not keen on centralized exchanges with BSQ holdings voting / setting the direction of the Bisq DAO.

**Comment by pazza83** [comment] 2022-05-01 20:54
Closing as rejected.

**Closed as completed by pazza83** 2022-05-01 20:54 UTC
Labels: was:rejected, a:proposal
