### ISSUE TITLE
Lower Trading Fee

### ISSUE THREAD

**Issue by ifarnung** [bisq-network/proposals#126] opened 2019-10-09 11:11 UTC
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

**Proprosal to Lower Trading Fee**

On June 26th, in Proposal #99, Deltahandler proprosed to raise the trading fee as not enough BSQ tokens were being burned.  They were basing the new fee structure on a hopeful estimate of 20 million USD trading volume per month.  This would have generated a minimum of 80,000$ in fee revenue.  (https://github.com/bisq-network/proposals/issues/99)

The fee in BTC terms was raised from .004 BTC (.001 + .003) for maker+taker to .008 (.002 + .006) BTC for maker+taker.  A rise of 100% and at .6% for the taker plus mining fees, it looks to be a material cost.  On an order of 2.0 Bitcoins, 1.6 million sats are being taken in fees not including mining fees (at this large trade size, the mining fees become trivial, just as at small trade sizes [.01BTC] the trade fee is much smaller than the mining fees typically).

The fee in BSQ terms was raised from a round trip of 6.4 BSQ (1.6 maker + 4.8 taker BSQ) to 51 BSQ (13 maker + 38 taker BSQ) which is an astounding 800% raise in fees.  It's pretty clear that the BSQ fee was too low at .066%, but also seems clear to me and other traders that it's too high at .51%.

So it shouldn't surprise us that these much higher fees are working to discourage efficient trading on BISQ at the higher volume level.  
This, in my opinion, is mostly negatively affecting the Monero trade but that a big part of the BISQ volume.  Maybe it was too cheap before and it's too expensive now, it would be nice to find a happy balance!  Other users share my negative opinion of the increased trading fee, and I suggest reading what 'invertedbob' wrote in a thread called 'Fees skyrocketed?' 
 (https://bisq.community/t/fees-skyrocketed/8085/29)

Unfortunately, the trading volume trend has been down the last few months, I have personally noticed a severe decline in the Monero market in September.  The bulk of the trade (multiple 2.0 BTC trades) seems to have moved somewhere else, as the customers likely still have a need to convert XLM and BTC.

I think we can attract liquidity and trading by lowering the trading fee.

My background is in stock options market making at the Chicago Board Options Exchange where I worked for 10 years (2000-2010) before retiring due to a combination of being made obsolete by algorithmic trading and stacking enough sats to be free of the modern variety of (corporate) slavery.

So who cares so much about these fees?  Meapistol wrote in Proposal #99 _"The BTC price can easily change 20% in a day and changes far more than the fee within the trading window. Fees are of no importance to traders, in particular in comparison with the friction that Bisq has."_

While I can understand the sentiment, I couldn't disagree more.  The volatility of the BTC price is random (let's assume for simplicity) but the fee is very much a tax that always gets collected.  [Example: When your Citibank ATM charges you a 3% foreign transaction fee, you can never get a good exchange rate with them.]  It's especially important for the market makers as they must charge it back from their customers anyway!

Why do we need market makers anyway? I thought this was peer to peer?  Can't we cut out the middleman?  While it would be nice, take a look at Ebay, it's overwhelmingly professional sellers catering to regular customers.  The BISQ customer (Taker) wants to fire up BISQ, see what the best offer is, and make their trade.  It's nice when they happen to meet another person just like them with the exact opposite desire and the exact same amount, but it's somewhat rare.  Great recent example, there are no offers in the BRL order book, everyone wants to buy! 

This is where the market makers come in.  Their BISQ is on 24/7, they have created a bunch of offers that customers might be interested in taking, and there are just as happy buying or selling as their goal is a kind of two way trade or maybe a one-way circular trade involving another exchange.  For example, one could Sell BTC on BISQ, getting cash to a bank account, and then restocking their BTC BISQ account with purchases on a regulated exchange with a bank wire.

Market makers like me are on BISQ to trade to make a profit, using their bankroll and willingness to buy or sell at a premium to the spot price to stack more sats. Their function is provide liquidity when the customer wants it.  For example, I just got an email from a frequent trade partner that they want to buy another .125 BTC, so I will fund my wallet, set up the offer, and charge him X% for the trouble.  The hope is that there are many market makers like me competing with each other driving the fees charged by us middlemen down as close to the cost as anyone is willing.

So to make a profit, the market maker needs to charge the taker for the fees s/he is paying, as well as the fees that another exchange is charging (for example to go buy the Monero you need to send), as well as mining fees and finally his/her profit.  There's additional risk in the volatility of the assets but like I said before, that is more or less random and over the long run washes out to even.  But the fees never stop adding up, and those are charged directly to the customer.  Another material cost is the lost BSQ fees when you cancel an order to free up your 'Reserved Bitcoin'.  Let's say you make an offer for 2.0 BTC, pay your fees in BSQ (76$), and you never make a trade on that offer.  When you cancel, your BSQs are gone.

This is why you see the market about 3% wide in the XMR order book.  I've been quoting it narrower than anyone in there for at least a few weeks and really am not seeing many trades.

If a customer has to pay 1.4% over spot for XMR plus another .6% in trading fees, it's no wonder that they would look for a cheaper substitution.  With lower fees, the market makers are able to tighten their spreads.  So I would expect the offers to be more like 1% over spot, and hopefully even narrower.

**Conclusion:**

Reduce the fees as a way to reduce the market spread so that customers feel better about trading on BISQ.  If we cut the fees in half, and that causes the volume to more than double, then it's a win-win situation as BISQ collects more fees, and customers pay less.

**Final Proprosal:**

**Lower Trading Fees
Maker: .001 BTC  Taker .003 BTC
Maker: 5 BSQ per BTC  Taker: 15 BSQ per BTC**

**Comment by m52go** [comment] 2019-10-09 11:17
I haven't read through the proposal in detail, but since the proposal phase is ending soon, note that fees are DAO parameters. If you have specific numbers in mind, which it looks like you do, you should make DAO parameter change proposals with those targets.

With a generic proposal, even if it's approved by voters, fees won't be changed until parameter change proposals are approved, which won't be possible until the _next_ cycle ends.

**Comment by ifarnung** [comment] 2019-10-09 11:28
@m52go Yes, I would propose the 4 parameters to be changed (BTC Maker Fee, BTC Taker Fee, BSQ Maker Fee, BSQ Taker Fee) but thought I would let people respond.

**Comment by wiz** [comment] 2019-10-09 11:29
> My background is in stock options market making at the Chicago Board Options Exchange where I worked for 10 years (2000-2010) before retiring due to a combination of being made obsolete by algorithmic trading and stacking enough sats to be free of the modern variety of (corporate) slavery.

Wow, out of all the software engineer cypherpunk geeks here working on this decentralized trading platform, you might be the only actual "trader" around :wink:

I don't know the financial incentives at play well enough to conclude for myself if raising trading fees affected the BSQ market over the past few months, or perhaps it was a combination of other factors such as the Bitcoin market in general, or the issues caused by 0.01 BTC trade limits. And the other part of me feels like we are the FED voting to adjust interest rates :joy:

But I'm in this for the long run, and I think lowering fees, at least for the short term could be helpful for growth and launching Bisq in new markets. We should be cheaper than centralized exchanges if possible.

I think you should make the 4 parameter changing proposals in the DAO for this cycle and let them be voted on. If it doesn't pass we can always discuss it more and vote again next cycle.

**Comment by mpolavieja** [comment] 2019-10-09 12:28
@ifarnung is not alone, I was a market maker for more than 10 years on european stocks.  I don´t know if the volume decrease is due to the fee increase, but I share and agree with 100% of his concerns.

However, I have to say that market makers are centralized points for the BTC-fiat pairs, in the sense that banks can easily track most Bisq users by tracking just a few market makers.

**Comment by ifarnung** [comment] 2019-10-09 12:40
Great point @mpolavieja about the market makers being centralized points, and in the case of a banking rail, they will exchange possibly sensitive personal information.

**Comment by sqrrm** [comment] 2019-10-09 12:47
Comparing the Bisq fees to other exchanges they don't seem to be that out of line. The current fees on Bisq, per BTC, are:
```
BTC maker fee: 0.0020 
BTC taker fee: 0.0060
BSQ maker fee: 13.00
BSQ taker fee: 38.00
```
With the current BSQ price that's a maker fee around 0.0013 and taker fee at 0.0038, which is higher than what we have been aiming for. Lowering makes sense even with the previous thinking.

Perhaps it's worth lowering more to see if that would drive more trading. In that case I would suggest only lowering the fees in BSQ since that's what any market maker would be using. I suspect that the fees don't matter as much to casual traders compared to the friction of using Bisq at all. My suggested fees would be:
```
BTC maker fee: 0.0020 
BTC taker fee: 0.0060
BSQ maker fee: 7.00
BSQ taker fee: 21.00
```

Note that the proposal in the OP seem to have a decimal off for the BTC fees.

**Comment by ifarnung** [comment] 2019-10-09 12:55
@sqrrm I was using a % for the BTC fees but I edited now to the amount of BTC to make it more clear and to match your table.

I agree that to the smaller dollar amount traders, it's likely not worth the effort and expense to acquire around 20-50 BSQ, so maybe a heavy BSQ trading fee discount is the best way to segregate the different trading groups.  Both Makers and Takers in a 2.0 BTC trade would be highly incentivized to get some BSQ for the fees.

**Comment by MwithM** [comment] 2019-10-09 14:27
Trading fees do matter. So we shouldn't be making radical changes in this parameter unless it's really necessary. I didn't like raising fees 100% on the last proposal (although I expected a higher decrease in trading volume) and I wouldn't like to see we cut them by half now.

Traders need to understand that BSQ is very important for Bisq. I'm very positive about making the use of BTC for trading fees very expensive, but do we know % of trades with trading fees paid in BSQ vs BTC? Is it true that small trades are not bothering to use BSQ?

**Comment by sqrrm** [comment] 2019-10-09 14:36
@MwithM Last time we changed the BSQ fees to approximately 0.1% fee for makers and 0.3% for takers. Since BSQ/BTC rate is not fixed we will have to change this fee monthly to keep it at those rates. We should at least lower the BSQ fees to be in line with our target.

**Comment by chimp1984** [comment] 2019-10-09 16:09
> feels like we are the FED voting to adjust interest rates

It is more like the contributors decide how much they want to be investors and how much they want to be able to sell of their earned BSQ. 

E.g. if fees are too low not much demand from traders is created so contributors will have it harder to sell BSQ and are forced to keep their BSQ as investors. So it is a dangerous trade-off to goo too low with the fees. Too high fee -> we lose traders, too low fees -> we lose contributors.

The volume rise over the past 6 months correlates with the global BTC (and XMR) market IMO. It was very bullish until July/August, now it seems we entering a bearish market again (hope not). Bisq had always lower volume when market went bearish and rise in volume when it was bullish. Most Bisq users are more on the long side and holders.   

Lets look at current fee costs for a maker:
A 2 BTC (about 16389 USD) trade costs atm 31 USD if BTC is used for fee and 22 USD if BSQ is used. That is 0.189% of trade volume if BTC is used and 0.134% if BSQ is used.
So yes we are a bit over our target (0.1% for BSQ for maker).

I suggest to reduce to:
```BSQ maker fee: 10.00
BSQ taker fee: 30.00```

**Comment by chimp1984** [comment] 2019-10-09 16:26
> We should be cheaper than centralized exchanges if possible.

That is not likely to be feasible. Centralized exchanges are racing to 0 fee (some have already) and doing their business with other revenue streams (altcoin listing costs, and some or many probably frontrunning, user data business,... - and in future they convert to banks and do benefit from that privileged position).

**Comment by ifarnung** [comment] 2019-10-09 17:31
Thanks for the feedback, and it seems there is some consensus around lowering the fees closer to the .1% and .3% target.  Based on the current prices, that would be 8-9 BSQ for maker and around 26 BSQ for taker.  So I will submit the parameter changes and the DAO stakeholders can vote in the next few days.  Thanks for taking the time to respond and I now have a clearer picture of the BISQ vision regarding fees.

**Comment by chimp1984** [comment] 2019-10-09 17:35
> that would be 8-9 BSQ for maker and around 26 BSQ for taker.

On which BSQ price is that based on?
Current average is 0.85 USD (as BTC was going down). So I think the 0.1% is about 10 BSQ.

**Comment by ifarnung** [comment] 2019-10-09 17:37
I was using 1 BSQ = 1 $ and the current price of BTC $8,500.  .01% = $8.5  .03% = $26.5

**Comment by ifarnung** [comment] 2019-10-09 17:54
I guess I'm now a little confused as I last read that for cycle 6  1.00 USD per 1 BSQ.  (https://github.com/bisq-network/compensation/issues/364)

But I see that was at the completion of the last cycle, and if I look today at the DAO tab:
![image](https://user-images.githubusercontent.com/55181240/66506913-e0fba580-ead6-11e9-8dd9-cfa0a1b550c7.png)
(0.86$)

So what rate should compensation requests be calibrated to?

**Comment by chimp1984** [comment] 2019-10-09 18:07
The price for the cycle was used to have a consensus about the amount requested by all contributors, it was taken at the beginning of the cycle and unfortunately BTC price went down in the past weeks quite a lot, so the BSQ to USD price. For fees I see no reason why we should use such a snapshot price instead using the current price seems reasonable.

**Comment by ifarnung** [comment] 2019-10-09 21:26
Ok, I submitted the parameter changes for just the BSQ Maker and Taker Fee to 10 BSQ and 30 BSQ.  Thanks again for all the feedback.

**Comment by sqrrm** [comment] 2019-10-09 22:15
@ifarnung Thank you for a constructive discussion that probably cleared things up a bit for some people. Since we'll have to keep changing the BSQ fee as prices change we'll probably have this discussion again, but with new people. At least then we can point to this discussion.

I also think it would be very interesting to know how much the fee affect different Bisq user types' propensity to trade. Might not be that easy to find out since it's hard to get data on anonymous users :)

**Comment by flix1** [comment] 2019-10-15 08:01
Absolutely agree with @ifarnung that we should try to keep fees competitive and market makers happy. 

Growing volumes should prioritized over BSQ breakeven for some time. Bisq is still much to small a market to attempt to make it profitable at the expense of slowing down growth.

**Comment by flix1** [comment] 2019-10-16 12:21
![image](https://user-images.githubusercontent.com/4233784/66918627-0f6e0900-f020-11e9-8a64-81629459b704.png)

A little calculation of market maker profits. Of course many premises (volume, frequency, etc) might be wrong...

**Comment by ifarnung** [comment] 2019-10-16 12:37
@flix1 I don't think this parallels reality for the market maker at all.  For example, in practice, the premium over spot generally goes down the bigger the amount of BTC. So you may be able to charge 7% over for a .01 (though I pretty rarely see that trade, and only if you are selling BTC, therefore including chargeback risk), it would be tough to sell .5 BTC for 7% over spot, and you would have to wonder at that point if there wasn't some trick on the other end of the trade.

**Comment by chimp1984** [comment] 2019-11-06 22:12
@mpolavieja As fee has been adjusted in last voting cycle I guess that can be closed as accepted.

**Comment by mpolavieja** [comment] 2019-11-06 22:21
Yeah, I was about to close it and forgot. sorry.

**Closed by mpolavieja** 2019-11-06 22:21 UTC
Labels: was:approved
