### ISSUE TITLE
Require DAO vote and application fee to add new crypto assets, and call DAO vote to keep or remove currently listed crypto assets

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#159] opened 2019-12-28 15:01 UTC
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Based on the excellent points raised in proposals #153 and #158, I propose to greatly simplify the crypto asset listing policy of Bisq as follows:

1) Delist all crypto assets other than Bitcoin, Monero, and BSQ
2) Require a DAO proposal and DAO vote to add new crypto assets, together with a non-refundable application fee of 1000 BSQ using Proof of Burn (can be waived with DAO approval)

The simple truth is that the only crypto assets that matter to Bisq users are Bitcoin and Monero. If another asset is actually worth our time, the DAO proposal process can be used, together with the application fee to cover the costs of even discussing the listing the asset. This discourages random shitcoiners from wasting our time just so they can list their scamcoin, but allows new projects that are both serious and interesting (like Blockstream Liquid L-BTC maybe?) to properly be discussed and approved.

**Comment by FKrauss** [comment] 2019-12-28 16:39
I agree with all except the fee should be 10000 bsq instead.
1000 could be for assets that were in bisq previously, got delisted (through this proposal only) and then approved by the Dao

**Comment by chimp1984** [comment] 2019-12-28 16:43
I do not think that is a good idea as there are valuable coins like Namecoin, Decred, Sia, etc. which even if not much traded are projects which we should support. If we do DAO voting for adding we get spammed with advertising why some shitcoin is so great. I think the existing tools should work and to make a full stop on adding new coins should be enough, specially this is justified with adjustments how we want to spend money.

**Comment by SimoneBovi** [comment] 2019-12-28 16:58
I totally agree with the purpose of this proposal. Honestly, I would not even consider spending much time or the DAO to list more coins in the future, this is a waste of effort to me and there are other things to prioritize.

@chimp1984 who decides, and based on what, which are the valuable coins? And what are the objective reasons that imply that we should support them?

I think that the @wiz approach is the only one we should follow in case we collectively think that the coins list should not be fixed once and for all. Quoting somehow @FKrauss, I think 10000 BSQ should be used for every new asset, independently of previous listings. 1000 BSQ is too low for me.

To be clear, I would only keep BTC and BSQ, but I understand that also XMR could have some useful use cases and has a lot of trading volume.

**Comment by FKrauss** [comment] 2019-12-28 17:47
@SimoneBovi I take back the 10k BSQ fee idea. It messes up with our incentives as contributors. It pumps the bsq price so much that it is way more profitable to come up bisq, work for a couple k BSQ then bring some shitcoin in that will need to buy those BSQ off the market (regardless of it getting accepted or not).

I agree with wiz' original idea. I would just merge it with Chimp's

Some assets should remain but we do need a proper cleanup of the assets we have listed.

Let's start a list of assets that should remain:

- xmr

**Comment by RiccardoMasutti** [comment] 2019-12-28 19:38
> Let's start a list of assets that should remain:

BTC, XMR, DOGE, GRIN

**Comment by wiz** [comment] 2019-12-28 19:58
> there are valuable coins like Namecoin, Decred, Sia, etc.

@chimp1984 sure - this is what I intended, to revert to a clean state and allow the DAO to decide what coins to list

> BTC, XMR, DOGE, GRIN

@RiccardoMasutti ah yes DOGE how could I forget the most important asset :joy:

> But at the same time, I think we should allow most cryptocurrencies to be present on Bisq

@RiccardoMasutti I think chimp already summarized the issues in his proposal - we need a new system. I am simply proposing we revert to a clean slate and have people propose the ones we should add, and then we can vote on those proposals

> I agree with wiz' original idea. I would just merge it with Chimp's

let's start by amending this proposal to include the assets that chimp mentioned

**Comment by justinvforvendetta** [comment] 2019-12-28 21:12
whats the point of a DEX if you are going to limit the coins available for trading? seems quite literally counter-productive.

**Comment by carsenk** [comment] 2019-12-28 21:28
> whats the point of a DEX if you are going to limit the coins available for trading? seems quite literally counter-productive.

Agreed, limiting themselves in a centralized fashion like this, will be their downfall. 

No one will want to support a project like this. I know as an altcoin dev, my community won't either.

**Comment by justinvforvendetta** [comment] 2019-12-28 21:33
@carsenk the only way this dex can grow is if altcoins are free to make pr's and market bisq freely to their communities. (or bisq starts spending a ton on advertisements) otherwise it will remain volumeless and even have a stigma of anti-altcoin.

**Comment by FKrauss** [comment] 2019-12-28 22:34
@sunerok
If that is true bisq would be 5x its size by now. The reality is that apart
from xmr, all the other coins just bring us work and no volume nor new
users. I'm yet to see someone who came for the Altcoins and stayed for the
Bitcoin

I also disagree with you that the point of a dex should be to list
everything under the sun.

Supporting these adds unnecessary organizational complexity to the project
and wastes our time in evaluating new proposals and cleaning up the dead
bodies as many, if not most, of these coins are already dead.

Who's supposed to keep track of all the coins listed in bisq that died this
month?

**Comment by wiz** [comment] 2019-12-28 22:35
> whats the point of a DEX if you are going to limit the coins available for trading? seems quite literally counter-productive

are you confusing decentralization with a lack of governance? the point of decentralization is to avoid regulation by nation state governments. the point of the bisq community having a vetting process for what crypto assets to list is to prevent bisq from supporting scams and shitcoins.

> the only way this dex can grow is if altcoins are free to make pr's

anyone can submit a listing if they pay the application fee. the point of charging an application fee to submit new crypto asset listings is to financially disincentivize shitcoiners from wasting the bisq community's time. 

too bad we can't charge a fee for posting on github, then shitcoiners wouldn't bother us so much :wink:

**Comment by buzzkillb** [comment] 2019-12-28 23:15
You could always move BISQ to private gitlab and host yourself if other cryptocurrency dev opinions bother you so much. Is Verge dead? No. Is Denarius dead? No. Is Ethereum dead? No.

As someone who uses BISQ and was telling Denarius community to check this out, its quite nuts to only want BTC and XMR on this and shun everything else.

**Comment by justinvforvendetta** [comment] 2019-12-29 00:20
@FKrauss why would it be 5x its size? isnt it just a bit of code, which is basically text? its not like it has to have each coins daemon running at the same time...

**Comment by c5yal8r** [comment] 2019-12-29 00:31
@buzzkillb you are the reason why I looked into BISQ.  Everything looked promising at first, but It’s clear to me now that this DEX will die off.  I understand that rules and regulations are needed.  No premine/ninja mine/insta mine on BISQ, because according to them, that’s a scam. Surprised you didn’t add any crypto with dev fees.  So how is an honest community supposed to even pay for listings then without some sort of fund?  Easy, scammers will pay cause they will role over funds from previous scams.

**Comment by alexej996** [comment] 2019-12-29 02:49
I need to strongly disagree on this.

I don't care for altcoins generally, I only use Monero, but I don't think that this is a good idea. We can't know what future altcoin turns out popular and useful and we shouldn't need to research this every time a new crypto comes out.

Blockchain is still a very new technology and very developing field. We shouldn't fight new innovations in this field, but fight the current corrupt fiat system instead. Altcoins are not our enemy, government and banks are.

Many altcoins are quick cash grabs, I know, but some must be real attempts at innovation. We shouldn't generalize and discriminate against new assets, instead I believe we should make it easier to add more altcoins and remove our responsibility as contributors to judge rightfully which altcoins are good and which are bad.

I think less governance in this case is better. Optimally Bisq should allow altcoins to be added from within the app itself if possible and not require any effort from devs to merge PRs. Listing fee should only be there for anti-spam reasons.

**Comment by MwithM** [comment] 2019-12-29 09:04
I think #153 was good enough. As long as Bisq removes all the coins that haven't been traded enough last 3 months and to propose a new altcoin the altcoiner had to pay an amount that covers dev expenses and prevents spam, Bisq altcoins would be reduced to a fair amount and even not traded coins would generate revenue. That payment could be recovered for the altcoiner, at least up to a 75% if the trading revenue for Bisq was worth it.

I think that with the current trading model, filter scams before they're traded makes sense not only because of ethics, but also because they suppose liabilities to this project.

**Comment by chimp1984** [comment] 2019-12-31 04:06
@wiz 
By your DAO removal proposals you would remove them forever if they get accepted. No way to enable them after removal.

**Comment by m52go** [comment] 2019-12-31 07:56
> they suppose liabilities to this project.

I think this is the core issue here. Currently there is a judgment made on whether or not an asset should be added. This involves developer time without much payoff, and in the case of annoying token developers, even more developer time without much payoff.

Anyway, obviously, such judgments can be controversial. But maintainers are the ones who merge new assets based on this judgment, so in theory, any issues would be traced back to them. As a result, at this point (and however flawed), their judgments are the only ones that matter.

The only way to avoid this is to make it possible to list assets without maintainer involvement, as  alexej996 mentioned, so that maintainers cannot possibly be held responsible regardless of how great or crappy the asset is.

Until that happens, it only makes sense to limit asset listing as maintainers deem appropriate.

If that doesn't seem to align with the spirit of Bisq...well, lots of things didn't, until they did: arbitration, compensation, and a bunch of other things. Asset listing conventions is just be another one of those items.

**Comment by user718141** [comment] 2019-12-31 23:15
Yes go for the scam coin BSQ and crime coin XMR that pays off.

**Comment by Xa5r** [comment] 2020-01-01 22:46
Wow this is crazy @wiz !
As a long Bisq supporter of the first days, I strongly disagree your intentions here.
What king of DEX should bisq be?
A DEX with only XMR/BTC as crypto pair? What is then the sense of bisq?
I always mention bisq every when it comes to the exchanges topic, and spread the word in altcoin communities, but with this idea bisq will get the label as Anti-Altcoins.
Probably you don't care because you call all altcoins disrespectful as "shitcoins".

From my side I feel betrayed in my support in the values bisq is fighting for.

A listing fee to compensate dev time is fine.

**Comment by aerth** [comment] 2020-01-02 04:31
what a joke

**Comment by wiz** [comment] 2020-01-02 06:25
Wow, I think many people misunderstand my proposal and were triggered. I am simply saying we should require DAO approval for all crypto assets on Bisq, and add an application fee to review new ones.

I've made the appropriate DAO proposals to de-list the current assets, so there will be a vote to keep or remove the current crypto assets. This proposal is mostly about formalizing the application fee policy carrying over from discussion in #153 that put current listing of new assets on hold. By requiring an application fee, it will prevent the "shitcoins" as I call them from wasting our time. Of course, the DAO can waive the application fee for any crypto assets it deems worthy.

I don't understand why so many people are reacting negatively. If you want to keep the assets, just vote to keep them. If you want to remove the assets, then vote to remove them. I am simply calling for a vote.

**Comment by anonbisq** [comment] 2020-01-02 09:56
When are you going to suggest to remove "unprofitable" markets and payment metods as well? And what a bureaucracy to list/delist. Is an official representative going to pay that fee you think? And the fee is redeemed when delisted? No, you imply to keep XMR, BTC and BSQ only.

**Comment by MwithM** [comment] 2020-01-11 12:20
I'm going to vote to remove all assets except those that @flix1 is trying to boost with [bountys](https://github.com/bisq-network/growth/issues) and DAI. Maybe I don't llike all of them, but as long as they are not completely against Bisq philosophy and can generate profit, Bisq should welcome altcoins.

Application fee should be reimbursed if the asset is profitable.

**Comment by chimp1984** [comment] 2020-01-12 16:20
Please be aware that removing an asset by DAO voting cannot be undone (e.g. cannot be added anymore later)! 

I hope DAO voters take their due dilligence serious and don't vote if they don't understand the full context.

**Comment by MwithM** [comment] 2020-01-13 09:03
Then I'll just vote to remove Bitcoin Rhodium, but if possible, there should be a way to automatically vanish from Bisq client not traded assets after a period of three cycles or so.
They generate noise and are a free ad.
Let me know if there are reasons to remove other assets than Rhodium. I would also vote to remove assets with no trades after 3 or 6 months but I don't want to lose time looking at which are these coins.

**Comment by flix1** [comment] 2020-01-13 09:12
I would not remove any asset that has been actively traded in the past 3 months.

**Comment by flix1** [comment] 2020-01-13 11:09
Since we are on the topic of listing and de-listing assets... There are 3 types of coins which I think could do very well on Bisq:

1. Top 10 coins by volume
2. Privacy coins
3. Stablecoins

Nº 1 for obvious reasons. For nº 2 Bisq offers obvious advantages over all other exchanges and should dominate this market. Nº 3 allows a fast way to trade BTC for a fiat derivative while avoiding the problems of fiat payment systems.

**XMR** hits 1 and 2. ZEC probably makes sense 2.

**USDT** (Tether) is huge in volume. We should add it. It's a Bitcoin-based coloured coin based on omnilayer protocol. We could even have atomic swaps between USDT and BTC on Bisq.

**USDC** (USD Coin) also has large volumes. It's on Bisq, but with no activity... maybe a small effort should be made to kickstart it.

**Comment by Xa5r** [comment] 2020-01-13 23:01
Delisting after 3 months inactivity ok (I would say 4 months like it was before).
But there is one Coin you guys should always support.
Namecoin.
It's was created because of Satoshi and follows the philosophy of decentralisation.
Namecoin got delisted on most exchanges and bisq is someking the last resort if the last small centralized exchanges disappeare.
Then there is no easy way to get NMC to register Name's on it's blockchain.

**Comment by wiz** [comment] 2020-01-13 23:05
Thanks everyone for the excellent discussion. Please understand my intention was not to delist assets from Bisq which have wide support, but instead to discuss the matter and call a vote for each one individually and let the community re-consider and decide which assets to keep and which to drop. I made many individual proposals to delist each individual asset, so to clarify the generic proposal vote for this is specifically for the "require DAO vote" + "require application fee" to review new assets.

Vote responsibly :wink:

**Comment by MwithM** [comment] 2020-01-13 23:58
> Nº 1 for obvious reasons. For nº 2 Bisq offers obvious advantages over all other exchanges and should dominate this market. Nº 3 allows a fast way to trade BTC for a fiat derivative while avoiding the problems of fiat payment systems, so it is ideal for traders who do a large % of volume.

> Bisq really should dominate the Monero, ZEC markets and capture at least 10% of their volume. We really need to discover what is missing to make this possible. I find it quite astonishing that Bisq does less than 1% of XMR volume while KYC exchanges like Binance do 15%+.
> 
> **USDT** (Tether) is huge in volume. We should add it. It's a Bitcoin-based coloured coin based on omnilayer protocol. We could even have atomic swaps between USDT and BTC on Bisq.
> 
> **USDC** (USD Coin) also has large volumes. It's on Bisq, but with no activity... maybe a small effort should be made to kickstart it.

@flix1 I agree with your view but:
In the top 10 at coingecko there are assets like xrp that cannot even be considered cryptocurrencies and thus shouldn't be listed. Monero is out of that top ten so I imagine Bisq needs to create its own top ten where bch is not even considered for obvious and already known reasons.

Stablecoins are very useful but usdc and usdt are centralized currencies that I don't think they share Bisq values so it should be considered carefully if they ought to be listed. There could be legal implications too.
They are backed by fiat supposedly held in a bank account by a corporation. One call from the bad guys and these stablecoins are useless.

**Comment by Xa5r** [comment] 2020-01-14 05:27
Regarding Stablecoins, yes Stablecoins can't share the same values because they are always centralized.
But nevertheless I would support them because they are really useful and Fiat will become valuesless anyway.

Regarding "one call" yes you are right this can happen that they make your token valueless.
And this should be a reason to support multiple stablecoins.
As soon (for example) USDC will destroy the funds of Bisq user's, this will become public in any news and people will switch to other stablecoins. The companies are very afraid of such news because it's buisness based on trust heavily.
Because USDC is from Goldman Sachs who stole many funds from user's on poloniex, I would prefer TrueUSD which founders are from Google.

**Comment by MwithM** [comment] 2020-01-14 08:12
DAI and MOC are quite different models of stablecoins that could be eventually called cryptocurrencies and I think Bisq should focus on those.
In the meantime, at least it has to be made very clear that usdt and usdc are not cryptocurrencies if Bisq allows listing them as a pragmatic measure.

**Comment by flix1** [comment] 2020-01-14 09:48
@MwithM Yes stablecoins are centralized, but so are fiat bank payments. Bisq is a bridge. Bisq users deal with centralized systems every time they use Revolut, Faster payments, SEPA or Zelle....

From the point of view of UX, speed and privacy stablecoins are better than SEPA or WeChatPay. Intermes of volume they are huge and will be even bigger. I expect in the coming years many banks, governments and companies will issue stablecoins.

Being aware of the risks, I would not ignore the opportunities...

As a trading platform that cares about volume we should be aware that 90% of the volume is done by traders and speculators (just the same as in the FX world), not by industry hedgers or final users. 

Speculators and traders, especially high frequency traders, care a lot about speed of execution, APIs, liquidity and being able to lock in profits. Stablecoins serve this purpose well in several ways... "altcoin instant" as a payment method is the fastest settlement method thta Bisq has (at least until we can get atomic swaps or equivalent done).

**Comment by flix1** [comment] 2020-01-14 10:17
Having said all the above about caring about volume... I would not touch **XRP** with a 10ft pole even if it was the nº1 in volume. Nothing good can possibly come out of that mess.

**Comment by Xa5r** [comment] 2020-01-14 13:44
DAI stablecoin says itself it is completely decentralized, but I don't believe it.
The money must stay somewhere in a bank account or someone have to controll the asset value behind always meet the right value. There is a central point too.

**Comment by chimp1984** [comment] 2020-01-14 17:08
@wiz 
> instead to discuss the matter and call a vote for each one individually and let the community re-consider and decide which assets to keep and which to drop.

Your DAO proposals are for removing the asset which is implemented in the way that they are **removed forever**! That is why I try to explain here to vote responsible and only vote if one understands the consequences.
 
We will not change code for fixing bad vote results (e.g. important coins got kicked out). No dev effort worth for any change in the assets area, we have to deal how current system works and if people dont know how it works they should not try to change anything here as result might be not what was intended.

**Comment by aejontargaryen** [comment] 2020-01-15 03:10
Right. The way I understood DAO voted removal was to be used for serious removal of known blatant scams or some similar major issue...not for personal preference or lack of trade volume. That will just remove a major use case for BSQ in activating trial periods for listed assets.

I think everything is set up pretty darn well already as it is, aside from 0-trade assets. Under-traded assets are already removed from currency lists.. out of user view... until an asset fee is paid. It wouldn't hurt to remove 0-trade assets after a while, and I agree with @chimp1984. I think using the DAO-vote-to-remove-**an**-asset as a mass-extinction removal tool is counterproductive.

**Comment by sqrrm** [comment] 2020-01-15 12:59
I second @chimp1984 that this is an abuse of the DAO voting. In general DAO voting should in my mind only be used for serious issues that can't be solved by off chain discussions. I also agree with @aejontargaryen that these coins don't deserve to be considered scams.

**Comment by wiz** [comment] 2020-01-15 14:29
There's no such thing as an abuse of DAO voting. I merely called a vote, if the vote passes, great, if the vote is rejected, great, that's how voting works lol

**Comment by Xa5r** [comment] 2020-01-15 22:15
If I buy nealy all bsq token, can I vote to delist all coins I don't like? Or is it a abuse of DAO vote?

**Comment by aejontargaryen** [comment] 2020-01-16 07:54
I understand, and agree with the enthusiasm to filter down bisq and make it more efficient at fewer things. But to narrow the scope to singular coins is just folly and a waste of the broad reaching effects of the platform that has been built. I vote to if anything focus on categories of coins like @flix1 was mentioning. If Bitcoin functions well- so will Lightning related assets. If Monero functions well, so will other privacy assets. If cash functions well - so should stablecoins.

**Comment by aejontargaryen** [comment] 2020-01-16 08:05
+1 also for Namespace and other DNS coins.

**Closed** 2020-01-21 12:47 UTC

**Comment by mpolavieja** [comment] 2020-01-23 09:21
Rejected on DAO voting - Cycle 9
